#!/usr/bin/python3

import subprocess
import sys
import json


if len(sys.argv) < 3:
	print('Wrong sytax! usage: %s <path_to_cli> <path_to_installation>'%sys.argv[0])
	sys.exit(3)

wp_cli = sys.argv[1]
wp_dir = sys.argv[2]


ret = subprocess.check_output(['php', wp_cli, '--path=%s'%wp_dir, 'plugin', 'list', '--update=available', '--fields=name,update,status','--format=json'])
jdata = json.loads(ret.decode('utf-8'))

if len(jdata) == 0:
	print('No updates available')
	sys.exit(0)

print ('Updates availabled for: %s'%(','.join([x['name'] for x in jdata])))
sys.exit(1)